# Generated by Django 5.0.6 on 2025-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='file',
            field=models.FileField(upload_to='archives/'),
        ),
    ]
