# Generated by Django 5.0.6 on 2025-09-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('barre', 'Barre de fer'), ('rouleau', 'Rouleau de fer')], max_length=10)),
                ('longueur_critique', models.PositiveIntegerField(blank=True, default=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('prix_u', models.PositiveIntegerField(blank=True, null=True)),
                ('longueur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=10)),
                ('fer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer.fer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fer',
            constraint=models.UniqueConstraint(fields=('diametre', 'categorie'), name='unique_diametre_categorie'),
        ),
    ]
