# Generated by Django 5.0.6 on 2025-10-01 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepromo',
            name='nb_utilidation',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CodePromoUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='usesOrders.codepromo')),
            ],
        ),
    ]
