# Generated by Django 5.0.6 on 2025-10-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0003_alter_codepromouse_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepromo',
            name='nb_utilidation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
