# Generated by Django 5.0.6 on 2025-10-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0004_alter_codepromo_nb_utilidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepromo',
            name='nb_utilidation',
        ),
        migrations.DeleteModel(
            name='CodePromoUse',
        ),
    ]
