# Generated by Django 5.0.6 on 2025-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0006_codepromo_nb_utilidation_codepromouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepromo',
            name='expiration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='nb_utilidation',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
