# Generated by Django 5.0.6 on 2025-06-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fer', models.CharField(choices=[('barre', 'Barre de fer'), ('rouleau', 'Rouleau de fer')], max_length=10)),
                ('diametre', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('longueur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('fer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer.fer')),
            ],
        ),
    ]
