# Generated by Django 5.0.6 on 2025-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fer',
            name='type_fer',
        ),
        migrations.AlterField(
            model_name='fer',
            name='categorie',
            field=models.CharField(choices=[('barre', 'Barre de fer'), ('rouleau', 'Rouleau de fer')], max_length=10),
        ),
    ]
