# Generated by Django 5.0.6 on 2025-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer', '0002_remove_fer_type_fer_alter_fer_categorie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fer',
            constraint=models.UniqueConstraint(fields=('diametre', 'categorie'), name='unique_diametre_categorie'),
        ),
    ]
