# Generated by Django 5.0.6 on 2025-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer', '0005_fer_user_mouvement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fer',
            name='longueur_critique',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
    ]
