"""
Django settings for SiteDFmac project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# bendingiron.onrender.com
ALLOWED_HOSTS = ['bending-iron.com', 'www.bending-iron.com', 'localhost', '127.0.0.1']

# nouveau model de connexion
AUTH_USER_MODEL = 'auth_app.CustomUser'

# configuration de l'email
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'bendingiron.info@gmail.com'
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = 'bendingiron.info@gmail.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 465   # ou 587 si tu utilises TLS
EMAIL_USE_SSL = True   # True si port 465, sinon False
EMAIL_USE_TLS = False  # True si port 587
EMAIL_HOST_USER = 'contact@bending-iron.com'  # ton adresse mail complète
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'contact@bending-iron.com'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT')
    }
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# addresse acepter en production
CSRF_TRUSTED_ORIGINS = [
    "https://bending-iron.com",
    "https://www.bending-iron.com",
    "http://localhost",
    "http://127.0.0.1",
]

CSRF_COOKIE_DOMAIN = '.bending-iron.com'
SITE_ID = 1

# nouvelle route de login
LOGIN_URL = 'auth/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_site',
    'front',
    'auth_app',
    'produits',
    'usesOrders',
    'fer',
    'contact',
    'tinymce',
    'django.contrib.humanize',
    'partenaires',
    'archives',
    # 'forms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
]

ROOT_URLCONF = 'SiteDFmac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'contact.context_processor.unread_messages',
                'produits.contexte_processor.constante_global',
                'usesOrders.context_proccessor.panier_count',
                'usesOrders.context_proccessor.commandes_en_attente',
                'partenaires.context_proccessor.order_en_attente',
                'fer.context_processors.seuil_critique_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'SiteDFmac.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# ✅ URL des fichiers statiques
STATIC_URL = '/static/'

# ✅ Emplacement des fichiers statiques en développement
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ✅ Emplacement des fichiers statiques collectés (prod)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATIC_URL = 'static/'

# '''localisation des fichiers static'''
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

'''manipulation des medias'''
MEDIA_ROOT = os.path.join(BASE_DIR, "medias")

'''localisation des images'''
MEDIA_URL='/medias/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
