# Generated by Django 5.0.6 on 2025-06-16 10:02

import contact.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', "Demande d'information"), ('reclamation', 'Réclamation'), ('autre', 'Autre')], max_length=50)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('is_read', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contacts/files/', validators=[contact.models.validate_pdf])),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contact.contact')),
            ],
        ),
    ]
