# Generated by Django 5.0.6 on 2025-06-16 20:07

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/files/', validators=[contact.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('devis', 'Devis'), ('renseignements', 'Renseignements'), ('autre', 'Autre')], max_length=50),
        ),
    ]
