# Generated by Django 5.0.6 on 2025-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file_response',
            field=models.FileField(blank=True, null=True, upload_to='contacts/files/'),
        ),
    ]
