# Generated by Django 5.0.6 on 2025-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_file_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('devis_assemblage', "Devis d'assemblage"), ('devis_assemblage_pose', "Devis d'assemblage + pose"), ('renseignements', 'Renseignements'), ('autre', 'Autre')], max_length=50),
        ),
    ]
