# Generated by Django 5.0.6 on 2025-09-06 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenariats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('statut', models.CharField(default='en cours', max_length=255)),
                ('reduction', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('partenariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaires.partenariats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.PositiveSmallIntegerField(choices=[(1, '1ère tranche'), (2, '2ème tranche'), (3, '3ème tranche')])),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='partenaires.projet')),
            ],
            options={
                'ordering': ['tranche'],
            },
        ),
        migrations.CreateModel(
            name='ProjetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('prix_revient', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_u', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetitems', to='partenaires.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaires.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('projet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_items', to='partenaires.projetitem')),
                ('projet_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_order', to='partenaires.projetorder')),
            ],
        ),
        migrations.CreateModel(
            name='TraimentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_production', 'En production'), ('pret_pour_livraison', 'Pret pour livraison'), ('termine', 'Livraison termine')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_order_name', to='partenaires.projetorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='projet',
            constraint=models.UniqueConstraint(fields=('name', 'partenariat'), name='unique_name_partenariat'),
        ),
        migrations.AlterUniqueTogether(
            name='paiementprojet',
            unique_together={('projet', 'tranche')},
        ),
    ]
