# Generated by Django 5.0.6 on 2025-06-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userr',
            new_name='user',
        ),
    ]
