# Generated by Django 5.0.6 on 2025-10-01 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0002_codepromo_nb_utilidation_codepromouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepromouse',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codesuses', to='usesOrders.codepromo'),
        ),
    ]
