# Generated by Django 5.0.6 on 2025-06-20 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0004_remove_order_statut_traiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='traiment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
