# Generated by Django 5.0.6 on 2025-08-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0005_traiment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usesOrders.order')),
            ],
        ),
    ]
