# Generated by Django 5.0.6 on 2025-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0008_codepromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepromo',
            name='expiration',
            field=models.PositiveIntegerField(),
        ),
    ]
