# Generated by Django 5.0.6 on 2025-08-18 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0009_alter_codepromo_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepromo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
