# Generated by Django 5.0.6 on 2025-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0010_codepromo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
