# Generated by Django 5.0.6 on 2025-08-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0011_cart_remise_order_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuserinfo',
            name='mode_livraison',
            field=models.CharField(default='livraison sur chantier', max_length=255),
        ),
    ]
