# Generated by Django 5.0.6 on 2025-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0012_orderuserinfo_mode_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='prix_revient',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prix_revient',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
