# Generated by Django 5.0.6 on 2025-08-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0013_cartitem_prix_revient_orderitem_prix_revient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usesOrders.cart'),
        ),
    ]
