# Generated by Django 5.0.6 on 2025-08-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usesOrders', '0014_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
