# Generated by Django 5.0.6 on 2025-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_partenaire',
            field=models.BooleanField(default=0),
        ),
    ]
