# Generated by Django 5.0.6 on 2025-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenariats',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='partenariats',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
