# Generated by Django 5.0.6 on 2025-07-16 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0002_alter_partenariats_email_alter_partenariats_name'),
        ('produits', '0005_ferprice_prixrevient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenariats',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('statut', models.CharField(default='en cours', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField()),
                ('partenariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaires.partenariats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_u', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaires.projet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projet',
            constraint=models.UniqueConstraint(fields=('name', 'partenariat'), name='unique_name_partenariat'),
        ),
    ]
