# Generated by Django 5.0.6 on 2025-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0003_alter_partenariats_name_projet_projetitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaimenentProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='projet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
