# Generated by Django 5.0.6 on 2025-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0004_paimenentprojet_alter_projet_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaimenentProjet',
        ),
        migrations.AddField(
            model_name='projet',
            name='reduction',
            field=models.IntegerField(default=15),
        ),
    ]
