# Generated by Django 5.0.6 on 2025-07-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0005_delete_paimenentprojet_projet_reduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaires.projet')),
                ('projet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaires.projetitem')),
            ],
        ),
    ]
