# Generated by Django 5.0.6 on 2025-07-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0006_projetorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetitem',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetitems', to='partenaires.projet'),
        ),
    ]
