# Generated by Django 5.0.6 on 2025-07-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0008_alter_projetorder_projet_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetorder',
            name='projet_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='partenaires.projetitem'),
        ),
    ]
