# Generated by Django 5.0.6 on 2025-07-29 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0009_alter_projetorder_projet_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.PositiveSmallIntegerField(choices=[(1, '1ère tranche'), (2, '2ème tranche'), (3, '3ème tranche')])),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='partenaires.projet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tranche'],
                'unique_together': {('projet', 'tranche')},
            },
        ),
    ]
