# Generated by Django 5.0.6 on 2025-08-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0010_paiementprojet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetorder',
            name='projet_item',
        ),
        migrations.RemoveField(
            model_name='projetorder',
            name='quantite',
        ),
        migrations.CreateModel(
            name='ProjetOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('projet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_items', to='partenaires.projetitem')),
                ('projet_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_order', to='partenaires.projetorder')),
            ],
        ),
    ]
