# Generated by Django 5.0.6 on 2025-08-03 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0011_remove_projetorder_projet_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraimentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_production', 'En production'), ('pret_pour_livraison', 'Pret pour livraison'), ('termine', 'Livraison termine')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_order_name', to='partenaires.projetorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
