# Generated by Django 5.0.6 on 2025-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0012_traimentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetitem',
            name='prix_revient',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
    ]
