# Generated by Django 5.0.6 on 2025-06-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/images')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sous_categorie', models.CharField(blank=True, choices=[('etrier', 'Etrier pour toiture et bardage'), ('boulon', 'Boulon et ancrage a beton'), ('cintrage', 'Cintrage d extremite'), ('redrssage', 'Redressage et decoupage'), ('cadre', 'Cintrage de cadre')], max_length=20, null=True)),
                ('imageshop3d', models.ImageField(upload_to='produits/images')),
                ('imageshop2d', models.ImageField(upload_to='produits/images')),
                ('image_sous_categorie', models.ImageField(blank=True, null=True, upload_to='produits/images')),
                ('name_page', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, max_length=400, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='produits.categorie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('sous_categorie', 'nom'), name='unique_sous_categorie_nom'),
        ),
    ]
