# Generated by Django 5.0.6 on 2025-09-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/images')),
            ],
        ),
        migrations.CreateModel(
            name='FerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametre', models.CharField(choices=[('m6', 'M6'), ('m8', 'M8'), ('m10', 'M10'), ('m12', 'M12'), ('m14', 'M14'), ('m16', 'M16'), ('m20', 'M20'), ('m24', 'M24'), ('m27', 'M27'), ('m30', 'M30'), ('m32', 'M32'), ('taux', 'Taux transaction'), ('taxe', "Taxe de l'etat")], max_length=255, unique=True)),
                ('prixRevient', models.FloatField(blank=True, null=True)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sous_categorie', models.CharField(blank=True, choices=[('Etrier pour bardage et toiture', 'Etrier pour bardage et toiture'), ("boulon d'ancrage a beton", "boulon d'ancrage a beton"), ("cintrage d'extremite", 'Cintrage d extremite'), ('redressage et decoupage', 'Redressage et decoupage'), ('Cintrage de cadre', 'Cintrage de Cadre'), ('Cintrage de forme', 'Cintrage de Forme'), ('Quincaillerie', 'Quincaillerie')], max_length=255, null=True)),
                ('imageshop3d', models.ImageField(upload_to='produits/images')),
                ('imageshop2d', models.ImageField(upload_to='produits/images')),
                ('image_sous_categorie', models.ImageField(blank=True, null=True, upload_to='produits/images')),
                ('name_page', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, max_length=400, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='produits.categorie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('sous_categorie', 'nom'), name='unique_sous_categorie_nom'),
        ),
    ]
