# Generated by Django 5.0.6 on 2025-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='sous_categorie',
            field=models.CharField(blank=True, choices=[('Etrier pour bardage et toiture', 'Etrier pour bardage et toiture'), ("boulon d'ancrage a beton", "boulon d'ancrage a beton"), ("cintrage d'extremite", 'Cintrage d extremite'), ('redrssage et decoupage', 'Redressage et decoupage'), ('Cintrage de cadre', 'Cintrage de Cadre'), ('Cintrage de forme', 'Cintrage de Forme'), ('Quincaillerie', 'Quincaillerie')], max_length=255, null=True),
        ),
    ]
