# Generated by Django 5.0.6 on 2025-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_ferprice_alter_produit_sous_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferprice',
            name='diametre',
            field=models.CharField(choices=[('m6', 'M6'), ('m8', 'M8'), ('m10', 'M10'), ('m12', 'M12'), ('m14', 'M14'), ('m16', 'M16'), ('m20', 'M20'), ('m24', 'M24'), ('m27', 'M27'), ('m30', 'M30'), ('m32', 'M32'), ('taux', 'Taux transaction'), ('taxe', "Taxe de l'etat")], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ferprice',
            name='prix',
            field=models.FloatField(),
        ),
    ]
