# Generated by Django 5.0.6 on 2025-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_ferprice_diametre_alter_ferprice_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferprice',
            name='prixRevient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
